In [1]:
import numpy as np

In [4]:
# sigmoid function
def nonlin(x,deriv=False):
  if(deriv==True):
    return x*(1-x)
  return 1/(1+np.exp(-x))

In [16]:
# input dataset
X = np.array([ [0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1] ])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [18]:
!pip install tabulate
from tabulate import tabulate
print (tabulate(X))

-  -  -
0  0  1
0  1  1
1  0  1
1  1  1
-  -  -



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
# output dataset
y = np.array([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [22]:
print(tabulate(y))

-
0
0
1
1
-


In [19]:
#visualize the data
tab = np.concatenate((X, y), axis=1)
#join the X and y for ease of understanding
print(tabulate(tab, headers=['feature 1', 'feature 2', 'feature 3','results']))
# to appreciate contribution of tabulate, do and compare the results
print(tab) 

  feature 1    feature 2    feature 3    results
-----------  -----------  -----------  ---------
          0            0            1          0
          0            1            1          0
          1            0            1          1
          1            1            1          1
[[0 0 1 0]
 [0 1 1 0]
 [1 0 1 1]
 [1 1 1 1]]


In [7]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)


In [42]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
print(syn0)

l1error = []

for iter in range(10000):
# forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
# how much did we miss?
    l1_error = y - l1
    l1error.append(l1_error)




[[-0.92189043]
 [-0.66033916]
 [ 0.75628501]]
---------  ---------  --------  --------
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  

In [25]:
# multiply how much we missed by the
# slope of the sigmoid at the values in l1
l1_delta = l1_error * nonlin(l1,True)

In [43]:
# update weights
syn0 += np.dot(l0.T,l1_delta)
print("Output After Training:")
print (l1)
print(tabulate(l1error))

Output After Training:
[[0.68054663]
 [0.52396808]
 [0.458693  ]
 [0.30450325]]
---------  ---------  --------  --------
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.523968  0.541307  0.695497
-0.680547  -0.5239

In [29]:
!git --version


git version 2.42.0.windows.2


In [30]:
!git config --global user.name "felista47"
!git config --global user.email "manotifelista9@gmail.com"


In [32]:
!git init


Initialized empty Git repository in C:/Users/Admin/Desktop/ML_DataSet/part 3/.git/


In [33]:
!git add .

In [34]:
!git commit -m "learning neural network AI first class"

[master (root-commit) 0f42b62] learning neural network AI first class
 2 files changed, 476 insertions(+)
 create mode 100644 .ipynb_checkpoints/neuralNetcode-checkpoint.ipynb
 create mode 100644 neuralNetcode.ipynb


In [35]:
!git branch -M main

In [36]:
!git remote add origin https://github.com/felista47/artificial-intelligence-.git

In [39]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.


Everything up-to-date
