In [31]:
from tabulate import tabulate
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.2


The MNIST dataset is loaded directly from TensorFlow's datasets API. This dataset contains 70,000 grayscale images in 10 categories. The images show individual articles of clothing at low resolution (28 by 28 pixels), and the dataset is divided into 60,000 training images and 10,000 test images.

In [5]:
# step 2 Load dataset
mnist = tf.keras.datasets.mnist

In [6]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step


In [ ]:
print(tabulate(x_train))

A sequential model is created using TensorFlow's Keras API. The model has three layers:
An input layer that flattens the 28x28 images into a single array of 784 pixels.
A dense (fully connected) hidden layer with 128 neurons and the ReLU activation function.
An output layer with 10 neurons (one for each class) and the softmax activation function.

In [8]:
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Dense(128, activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10)
])

In [9]:
 predictions = model(x_train[:1]).numpy()


In [10]:
predictions


array([[-0.01323846, -0.02819641, -0.11707611,  0.45777038, -0.9262602 ,
        -0.1370661 ,  0.1852963 ,  0.44960538, -0.5553641 ,  0.25079912]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()


array([[0.09555787, 0.09413915, 0.08613314, 0.15304635, 0.03834831,
        0.08442844, 0.11654376, 0.15180182, 0.05556794, 0.12443326]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.4718509

In [14]:
model.compile(optimizer='adam',
loss=loss_fn,
metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8525 - loss: 0.4966
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9558 - loss: 0.1499
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9673 - loss: 0.1076
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9733 - loss: 0.0877
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9761 - loss: 0.0726


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9785 - loss: 0.0712


[0.07122504711151123, 0.9785000085830688]

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.1636270e-08, 9.3451478e-09, 4.4514677e-06, 2.6563823e-04,
        1.5068003e-12, 2.3990337e-06, 2.5491536e-14, 9.9972576e-01,
        1.0925407e-06, 5.6131580e-07],
       [1.5123831e-07, 3.7150498e-04, 9.9960762e-01, 1.1540869e-05,
        4.2457688e-16, 2.6540681e-06, 5.4886296e-09, 1.3968564e-13,
        6.5658305e-06, 3.8182651e-12],
       [2.7223913e-07, 9.9854362e-01, 2.5155002e-04, 1.7503644e-05,
        2.0665277e-04, 1.3106699e-05, 7.8380916e-05, 5.5250590e-04,
        3.2590114e-04, 1.0448566e-05],
       [9.9980718e-01, 2.9814270e-10, 1.6194367e-04, 2.1928543e-07,
        1.5827666e-07, 5.1265674e-06, 5.9123367e-06, 2.3306743e-06,
        1.8538506e-07, 1.6956024e-05],
       [1.7098587e-06, 3.9863829e-10, 1.5304488e-05, 1.0907414e-07,
        9.9349868e-01, 3.8331414e-06, 3.8074813e-06, 7.1933013e-05,
        1.5044260e-06, 6.4031710e-03]], dtype=float32)>

In [19]:
!git config --global user.name "felista47"
!git config --global user.email "manotifelista9@gmail.com"


In [20]:
!git init


Reinitialized existing Git repository in C:/Users/Admin/Desktop/ML_DataSet/part 3/.git/


In [22]:
!git add .

In [23]:
!git commit -m "learning neural network AI with tensorflow mnist dataset"

[main 9ebe521] learning neural network AI with tensorflow mnist dataset
 7 files changed, 21201 insertions(+), 18 deletions(-)
 create mode 100644 .ipynb_checkpoints/Untitled-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/Untitled1-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/neural network tensorflow-checkpoint.ipynb
 create mode 100644 Untitled.ipynb
 create mode 100644 Untitled1.ipynb
 create mode 100644 neural network tensorflow.ipynb


In [24]:
!git branch -M main

In [27]:
!git remote add origin https://github.com/felista47/tensorflow-mnist-dataset.git

error: remote origin already exists.


In [26]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.


To https://github.com/felista47/artificial-intelligence-.git
   0f42b62..9ebe521  main -> main


In [29]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   neural network tensorflow.ipynb
	modified:   neuralNetcode.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [30]:
!git add .